// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/menu.proto

package menu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dish struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category        string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Calories        int32                  `protobuf:"varint,5,opt,name=calories,proto3" json:"calories,omitempty"`
	Proteins        int32                  `protobuf:"varint,6,opt,name=proteins,proto3" json:"proteins,omitempty"`
	Fats            int32                  `protobuf:"varint,7,opt,name=fats,proto3" json:"fats,omitempty"`
	Carbs           int32                  `protobuf:"varint,8,opt,name=carbs,proto3" json:"carbs,omitempty"`
	Ingredients     []string               `protobuf:"bytes,9,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	CookTimeMinutes int32                  `protobuf:"varint,10,opt,name=cook_time_minutes,json=cookTimeMinutes,proto3" json:"cook_time_minutes,omitempty"`
	Price           int32                  `protobuf:"varint,11,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Dish) Reset() {
	*x = Dish{}
	mi := &file_proto_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{0}
}

func (x *Dish) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dish) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Dish) GetCalories() int32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *Dish) GetProteins() int32 {
	if x != nil {
		return x.Proteins
	}
	return 0
}

func (x *Dish) GetFats() int32 {
	if x != nil {
		return x.Fats
	}
	return 0
}

func (x *Dish) GetCarbs() int32 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

func (x *Dish) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *Dish) GetCookTimeMinutes() int32 {
	if x != nil {
		return x.CookTimeMinutes
	}
	return 0
}

func (x *Dish) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{1}
}

type DishList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishList) Reset() {
	*x = DishList{}
	mi := &file_proto_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishList) ProtoMessage() {}

func (x *DishList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishList.ProtoReflect.Descriptor instead.
func (*DishList) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{2}
}

func (x *DishList) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

type CreateDishRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category        string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Calories        int32                  `protobuf:"varint,4,opt,name=calories,proto3" json:"calories,omitempty"`
	Proteins        int32                  `protobuf:"varint,5,opt,name=proteins,proto3" json:"proteins,omitempty"`
	Fats            int32                  `protobuf:"varint,6,opt,name=fats,proto3" json:"fats,omitempty"`
	Carbs           int32                  `protobuf:"varint,7,opt,name=carbs,proto3" json:"carbs,omitempty"`
	Ingredients     []string               `protobuf:"bytes,8,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	CookTimeMinutes int32                  `protobuf:"varint,9,opt,name=cook_time_minutes,json=cookTimeMinutes,proto3" json:"cook_time_minutes,omitempty"`
	Price           int32                  `protobuf:"varint,10,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateDishRequest) Reset() {
	*x = CreateDishRequest{}
	mi := &file_proto_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDishRequest) ProtoMessage() {}

func (x *CreateDishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDishRequest.ProtoReflect.Descriptor instead.
func (*CreateDishRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDishRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDishRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateDishRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateDishRequest) GetCalories() int32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *CreateDishRequest) GetProteins() int32 {
	if x != nil {
		return x.Proteins
	}
	return 0
}

func (x *CreateDishRequest) GetFats() int32 {
	if x != nil {
		return x.Fats
	}
	return 0
}

func (x *CreateDishRequest) GetCarbs() int32 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

func (x *CreateDishRequest) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *CreateDishRequest) GetCookTimeMinutes() int32 {
	if x != nil {
		return x.CookTimeMinutes
	}
	return 0
}

func (x *CreateDishRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type DishIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DishIdRequest) Reset() {
	*x = DishIdRequest{}
	mi := &file_proto_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DishIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishIdRequest) ProtoMessage() {}

func (x *DishIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishIdRequest.ProtoReflect.Descriptor instead.
func (*DishIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{4}
}

func (x *DishIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDishRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category        string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Calories        int32                  `protobuf:"varint,5,opt,name=calories,proto3" json:"calories,omitempty"`
	Proteins        int32                  `protobuf:"varint,6,opt,name=proteins,proto3" json:"proteins,omitempty"`
	Fats            int32                  `protobuf:"varint,7,opt,name=fats,proto3" json:"fats,omitempty"`
	Carbs           int32                  `protobuf:"varint,8,opt,name=carbs,proto3" json:"carbs,omitempty"`
	Ingredients     []string               `protobuf:"bytes,9,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	CookTimeMinutes int32                  `protobuf:"varint,10,opt,name=cook_time_minutes,json=cookTimeMinutes,proto3" json:"cook_time_minutes,omitempty"`
	Price           int32                  `protobuf:"varint,11,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateDishRequest) Reset() {
	*x = UpdateDishRequest{}
	mi := &file_proto_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDishRequest) ProtoMessage() {}

func (x *UpdateDishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDishRequest.ProtoReflect.Descriptor instead.
func (*UpdateDishRequest) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateDishRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDishRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateDishRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateDishRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateDishRequest) GetCalories() int32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *UpdateDishRequest) GetProteins() int32 {
	if x != nil {
		return x.Proteins
	}
	return 0
}

func (x *UpdateDishRequest) GetFats() int32 {
	if x != nil {
		return x.Fats
	}
	return 0
}

func (x *UpdateDishRequest) GetCarbs() int32 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

func (x *UpdateDishRequest) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *UpdateDishRequest) GetCookTimeMinutes() int32 {
	if x != nil {
		return x.CookTimeMinutes
	}
	return 0
}

func (x *UpdateDishRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_menu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_menu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_menu_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_menu_proto protoreflect.FileDescriptor

const file_proto_menu_proto_rawDesc = "" +
	"\n" +
	"\x10proto/menu.proto\x12\x04menu\"\xae\x02\n" +
	"\x04Dish\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bcalories\x18\x05 \x01(\x05R\bcalories\x12\x1a\n" +
	"\bproteins\x18\x06 \x01(\x05R\bproteins\x12\x12\n" +
	"\x04fats\x18\a \x01(\x05R\x04fats\x12\x14\n" +
	"\x05carbs\x18\b \x01(\x05R\x05carbs\x12 \n" +
	"\vingredients\x18\t \x03(\tR\vingredients\x12*\n" +
	"\x11cook_time_minutes\x18\n" +
	" \x01(\x05R\x0fcookTimeMinutes\x12\x14\n" +
	"\x05price\x18\v \x01(\x05R\x05price\"\a\n" +
	"\x05Empty\".\n" +
	"\bDishList\x12\"\n" +
	"\x06dishes\x18\x01 \x03(\v2\n" +
	".menu.DishR\x06dishes\"\xab\x02\n" +
	"\x11CreateDishRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1a\n" +
	"\bcalories\x18\x04 \x01(\x05R\bcalories\x12\x1a\n" +
	"\bproteins\x18\x05 \x01(\x05R\bproteins\x12\x12\n" +
	"\x04fats\x18\x06 \x01(\x05R\x04fats\x12\x14\n" +
	"\x05carbs\x18\a \x01(\x05R\x05carbs\x12 \n" +
	"\vingredients\x18\b \x03(\tR\vingredients\x12*\n" +
	"\x11cook_time_minutes\x18\t \x01(\x05R\x0fcookTimeMinutes\x12\x14\n" +
	"\x05price\x18\n" +
	" \x01(\x05R\x05price\"\x1f\n" +
	"\rDishIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbb\x02\n" +
	"\x11UpdateDishRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bcalories\x18\x05 \x01(\x05R\bcalories\x12\x1a\n" +
	"\bproteins\x18\x06 \x01(\x05R\bproteins\x12\x12\n" +
	"\x04fats\x18\a \x01(\x05R\x04fats\x12\x14\n" +
	"\x05carbs\x18\b \x01(\x05R\x05carbs\x12 \n" +
	"\vingredients\x18\t \x03(\tR\vingredients\x12*\n" +
	"\x11cook_time_minutes\x18\n" +
	" \x01(\x05R\x0fcookTimeMinutes\x12\x14\n" +
	"\x05price\x18\v \x01(\x05R\x05price\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x89\x02\n" +
	"\vMenuService\x12+\n" +
	"\fGetAllDishes\x12\v.menu.Empty\x1a\x0e.menu.DishList\x121\n" +
	"\n" +
	"CreateDish\x12\x17.menu.CreateDishRequest\x1a\n" +
	".menu.Dish\x12.\n" +
	"\vGetDishById\x12\x13.menu.DishIdRequest\x1a\n" +
	".menu.Dish\x121\n" +
	"\n" +
	"UpdateDish\x12\x17.menu.UpdateDishRequest\x1a\n" +
	".menu.Dish\x127\n" +
	"\n" +
	"DeleteDish\x12\x13.menu.DishIdRequest\x1a\x14.menu.DeleteResponseB\x18Z\x16menuservice/proto;menub\x06proto3"

var (
	file_proto_menu_proto_rawDescOnce sync.Once
	file_proto_menu_proto_rawDescData []byte
)

func file_proto_menu_proto_rawDescGZIP() []byte {
	file_proto_menu_proto_rawDescOnce.Do(func() {
		file_proto_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_menu_proto_rawDesc), len(file_proto_menu_proto_rawDesc)))
	})
	return file_proto_menu_proto_rawDescData
}

var file_proto_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_menu_proto_goTypes = []any{
	(*Dish)(nil),              // 0: menu.Dish
	(*Empty)(nil),             // 1: menu.Empty
	(*DishList)(nil),          // 2: menu.DishList
	(*CreateDishRequest)(nil), // 3: menu.CreateDishRequest
	(*DishIdRequest)(nil),     // 4: menu.DishIdRequest
	(*UpdateDishRequest)(nil), // 5: menu.UpdateDishRequest
	(*DeleteResponse)(nil),    // 6: menu.DeleteResponse
}
var file_proto_menu_proto_depIdxs = []int32{
	0, // 0: menu.DishList.dishes:type_name -> menu.Dish
	1, // 1: menu.MenuService.GetAllDishes:input_type -> menu.Empty
	3, // 2: menu.MenuService.CreateDish:input_type -> menu.CreateDishRequest
	4, // 3: menu.MenuService.GetDishById:input_type -> menu.DishIdRequest
	5, // 4: menu.MenuService.UpdateDish:input_type -> menu.UpdateDishRequest
	4, // 5: menu.MenuService.DeleteDish:input_type -> menu.DishIdRequest
	2, // 6: menu.MenuService.GetAllDishes:output_type -> menu.DishList
	0, // 7: menu.MenuService.CreateDish:output_type -> menu.Dish
	0, // 8: menu.MenuService.GetDishById:output_type -> menu.Dish
	0, // 9: menu.MenuService.UpdateDish:output_type -> menu.Dish
	6, // 10: menu.MenuService.DeleteDish:output_type -> menu.DeleteResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_menu_proto_init() }
func file_proto_menu_proto_init() {
	if File_proto_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_menu_proto_rawDesc), len(file_proto_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_menu_proto_goTypes,
		DependencyIndexes: file_proto_menu_proto_depIdxs,
		MessageInfos:      file_proto_menu_proto_msgTypes,
	}.Build()
	File_proto_menu_proto = out.File
	file_proto_menu_proto_goTypes = nil
	file_proto_menu_proto_depIdxs = nil
}
