// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: internal/proto/recommendation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PopularRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularRequest) Reset() {
	*x = PopularRequest{}
	mi := &file_internal_proto_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularRequest) ProtoMessage() {}

func (x *PopularRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularRequest.ProtoReflect.Descriptor instead.
func (*PopularRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_recommendation_proto_rawDescGZIP(), []int{0}
}

type Dish struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category        string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Calories        int32                  `protobuf:"varint,5,opt,name=calories,proto3" json:"calories,omitempty"`
	Proteins        int32                  `protobuf:"varint,6,opt,name=proteins,proto3" json:"proteins,omitempty"`
	Fats            int32                  `protobuf:"varint,7,opt,name=fats,proto3" json:"fats,omitempty"`
	Carbs           int32                  `protobuf:"varint,8,opt,name=carbs,proto3" json:"carbs,omitempty"`
	Ingredients     []string               `protobuf:"bytes,9,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	CookTimeMinutes int32                  `protobuf:"varint,10,opt,name=cook_time_minutes,json=cookTimeMinutes,proto3" json:"cook_time_minutes,omitempty"`
	Price           float32                `protobuf:"fixed32,11,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Dish) Reset() {
	*x = Dish{}
	mi := &file_internal_proto_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_internal_proto_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *Dish) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dish) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Dish) GetCalories() int32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *Dish) GetProteins() int32 {
	if x != nil {
		return x.Proteins
	}
	return 0
}

func (x *Dish) GetFats() int32 {
	if x != nil {
		return x.Fats
	}
	return 0
}

func (x *Dish) GetCarbs() int32 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

func (x *Dish) GetIngredients() []string {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *Dish) GetCookTimeMinutes() int32 {
	if x != nil {
		return x.CookTimeMinutes
	}
	return 0
}

func (x *Dish) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type PopularResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dishes        []*Dish                `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PopularResponse) Reset() {
	*x = PopularResponse{}
	mi := &file_internal_proto_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PopularResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PopularResponse) ProtoMessage() {}

func (x *PopularResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PopularResponse.ProtoReflect.Descriptor instead.
func (*PopularResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *PopularResponse) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

var File_internal_proto_recommendation_proto protoreflect.FileDescriptor

const file_internal_proto_recommendation_proto_rawDesc = "" +
	"\n" +
	"#internal/proto/recommendation.proto\x12\x0erecommendation\"\x10\n" +
	"\x0ePopularRequest\"\xae\x02\n" +
	"\x04Dish\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x1a\n" +
	"\bcalories\x18\x05 \x01(\x05R\bcalories\x12\x1a\n" +
	"\bproteins\x18\x06 \x01(\x05R\bproteins\x12\x12\n" +
	"\x04fats\x18\a \x01(\x05R\x04fats\x12\x14\n" +
	"\x05carbs\x18\b \x01(\x05R\x05carbs\x12 \n" +
	"\vingredients\x18\t \x03(\tR\vingredients\x12*\n" +
	"\x11cook_time_minutes\x18\n" +
	" \x01(\x05R\x0fcookTimeMinutes\x12\x14\n" +
	"\x05price\x18\v \x01(\x02R\x05price\"?\n" +
	"\x0fPopularResponse\x12,\n" +
	"\x06dishes\x18\x01 \x03(\v2\x14.recommendation.DishR\x06dishes2l\n" +
	"\x15RecommendationService\x12S\n" +
	"\x10GetPopularDishes\x12\x1e.recommendation.PopularRequest\x1a\x1f.recommendation.PopularResponseB Z\x1erecommend/internal/proto;protob\x06proto3"

var (
	file_internal_proto_recommendation_proto_rawDescOnce sync.Once
	file_internal_proto_recommendation_proto_rawDescData []byte
)

func file_internal_proto_recommendation_proto_rawDescGZIP() []byte {
	file_internal_proto_recommendation_proto_rawDescOnce.Do(func() {
		file_internal_proto_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_recommendation_proto_rawDesc), len(file_internal_proto_recommendation_proto_rawDesc)))
	})
	return file_internal_proto_recommendation_proto_rawDescData
}

var file_internal_proto_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_recommendation_proto_goTypes = []any{
	(*PopularRequest)(nil),  // 0: recommendation.PopularRequest
	(*Dish)(nil),            // 1: recommendation.Dish
	(*PopularResponse)(nil), // 2: recommendation.PopularResponse
}
var file_internal_proto_recommendation_proto_depIdxs = []int32{
	1, // 0: recommendation.PopularResponse.dishes:type_name -> recommendation.Dish
	0, // 1: recommendation.RecommendationService.GetPopularDishes:input_type -> recommendation.PopularRequest
	2, // 2: recommendation.RecommendationService.GetPopularDishes:output_type -> recommendation.PopularResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_recommendation_proto_init() }
func file_internal_proto_recommendation_proto_init() {
	if File_internal_proto_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_recommendation_proto_rawDesc), len(file_internal_proto_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_recommendation_proto_goTypes,
		DependencyIndexes: file_internal_proto_recommendation_proto_depIdxs,
		MessageInfos:      file_internal_proto_recommendation_proto_msgTypes,
	}.Build()
	File_internal_proto_recommendation_proto = out.File
	file_internal_proto_recommendation_proto_goTypes = nil
	file_internal_proto_recommendation_proto_depIdxs = nil
}
