// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/stats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitStatsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetCalories int32                  `protobuf:"varint,2,opt,name=target_calories,json=targetCalories,proto3" json:"target_calories,omitempty"`
	TargetWaterMl  int32                  `protobuf:"varint,3,opt,name=target_water_ml,json=targetWaterMl,proto3" json:"target_water_ml,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitStatsRequest) Reset() {
	*x = InitStatsRequest{}
	mi := &file_proto_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitStatsRequest) ProtoMessage() {}

func (x *InitStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitStatsRequest.ProtoReflect.Descriptor instead.
func (*InitStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{0}
}

func (x *InitStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InitStatsRequest) GetTargetCalories() int32 {
	if x != nil {
		return x.TargetCalories
	}
	return 0
}

func (x *InitStatsRequest) GetTargetWaterMl() int32 {
	if x != nil {
		return x.TargetWaterMl
	}
	return 0
}

type UpdateStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeltaCalories int32                  `protobuf:"varint,2,opt,name=delta_calories,json=deltaCalories,proto3" json:"delta_calories,omitempty"`
	DeltaWaterMl  int32                  `protobuf:"varint,3,opt,name=delta_water_ml,json=deltaWaterMl,proto3" json:"delta_water_ml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatsRequest) Reset() {
	*x = UpdateStatsRequest{}
	mi := &file_proto_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatsRequest) ProtoMessage() {}

func (x *UpdateStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatsRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateStatsRequest) GetDeltaCalories() int32 {
	if x != nil {
		return x.DeltaCalories
	}
	return 0
}

func (x *UpdateStatsRequest) GetDeltaWaterMl() int32 {
	if x != nil {
		return x.DeltaWaterMl
	}
	return 0
}

type UserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdRequest) Reset() {
	*x = UserIdRequest{}
	mi := &file_proto_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdRequest) ProtoMessage() {}

func (x *UserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdRequest.ProtoReflect.Descriptor instead.
func (*UserIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{2}
}

func (x *UserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type StatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetCalories  int32                  `protobuf:"varint,2,opt,name=target_calories,json=targetCalories,proto3" json:"target_calories,omitempty"`
	CurrentCalories int32                  `protobuf:"varint,3,opt,name=current_calories,json=currentCalories,proto3" json:"current_calories,omitempty"`
	TargetWaterMl   int32                  `protobuf:"varint,4,opt,name=target_water_ml,json=targetWaterMl,proto3" json:"target_water_ml,omitempty"`
	CurrentWaterMl  int32                  `protobuf:"varint,5,opt,name=current_water_ml,json=currentWaterMl,proto3" json:"current_water_ml,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{3}
}

func (x *StatsResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StatsResponse) GetTargetCalories() int32 {
	if x != nil {
		return x.TargetCalories
	}
	return 0
}

func (x *StatsResponse) GetCurrentCalories() int32 {
	if x != nil {
		return x.CurrentCalories
	}
	return 0
}

func (x *StatsResponse) GetTargetWaterMl() int32 {
	if x != nil {
		return x.TargetWaterMl
	}
	return 0
}

func (x *StatsResponse) GetCurrentWaterMl() int32 {
	if x != nil {
		return x.CurrentWaterMl
	}
	return 0
}

func (x *StatsResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{4}
}

var File_proto_stats_proto protoreflect.FileDescriptor

const file_proto_stats_proto_rawDesc = "" +
	"\n" +
	"\x11proto/stats.proto\x12\x05stats\"|\n" +
	"\x10InitStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0ftarget_calories\x18\x02 \x01(\x05R\x0etargetCalories\x12&\n" +
	"\x0ftarget_water_ml\x18\x03 \x01(\x05R\rtargetWaterMl\"z\n" +
	"\x12UpdateStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0edelta_calories\x18\x02 \x01(\x05R\rdeltaCalories\x12$\n" +
	"\x0edelta_water_ml\x18\x03 \x01(\x05R\fdeltaWaterMl\"(\n" +
	"\rUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xed\x01\n" +
	"\rStatsResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0ftarget_calories\x18\x02 \x01(\x05R\x0etargetCalories\x12)\n" +
	"\x10current_calories\x18\x03 \x01(\x05R\x0fcurrentCalories\x12&\n" +
	"\x0ftarget_water_ml\x18\x04 \x01(\x05R\rtargetWaterMl\x12(\n" +
	"\x10current_water_ml\x18\x05 \x01(\x05R\x0ecurrentWaterMl\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\a\n" +
	"\x05Empty2\xbc\x02\n" +
	"\fStatsService\x12:\n" +
	"\tInitStats\x12\x17.stats.InitStatsRequest\x1a\x14.stats.StatsResponse\x126\n" +
	"\bGetStats\x12\x14.stats.UserIdRequest\x1a\x14.stats.StatsResponse\x12>\n" +
	"\vUpdateStats\x12\x19.stats.UpdateStatsRequest\x1a\x14.stats.StatsResponse\x12=\n" +
	"\x0fResetDailyStats\x12\x14.stats.UserIdRequest\x1a\x14.stats.StatsResponse\x129\n" +
	"\x13DeleteStatsByUserId\x12\x14.stats.UserIdRequest\x1a\f.stats.EmptyBKZIgithub.com/Nurkanat-hub/GoProject/tree/back-end/stats-service/proto;protob\x06proto3"

var (
	file_proto_stats_proto_rawDescOnce sync.Once
	file_proto_stats_proto_rawDescData []byte
)

func file_proto_stats_proto_rawDescGZIP() []byte {
	file_proto_stats_proto_rawDescOnce.Do(func() {
		file_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)))
	})
	return file_proto_stats_proto_rawDescData
}

var file_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_stats_proto_goTypes = []any{
	(*InitStatsRequest)(nil),   // 0: stats.InitStatsRequest
	(*UpdateStatsRequest)(nil), // 1: stats.UpdateStatsRequest
	(*UserIdRequest)(nil),      // 2: stats.UserIdRequest
	(*StatsResponse)(nil),      // 3: stats.StatsResponse
	(*Empty)(nil),              // 4: stats.Empty
}
var file_proto_stats_proto_depIdxs = []int32{
	0, // 0: stats.StatsService.InitStats:input_type -> stats.InitStatsRequest
	2, // 1: stats.StatsService.GetStats:input_type -> stats.UserIdRequest
	1, // 2: stats.StatsService.UpdateStats:input_type -> stats.UpdateStatsRequest
	2, // 3: stats.StatsService.ResetDailyStats:input_type -> stats.UserIdRequest
	2, // 4: stats.StatsService.DeleteStatsByUserId:input_type -> stats.UserIdRequest
	3, // 5: stats.StatsService.InitStats:output_type -> stats.StatsResponse
	3, // 6: stats.StatsService.GetStats:output_type -> stats.StatsResponse
	3, // 7: stats.StatsService.UpdateStats:output_type -> stats.StatsResponse
	3, // 8: stats.StatsService.ResetDailyStats:output_type -> stats.StatsResponse
	4, // 9: stats.StatsService.DeleteStatsByUserId:output_type -> stats.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_stats_proto_init() }
func file_proto_stats_proto_init() {
	if File_proto_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stats_proto_goTypes,
		DependencyIndexes: file_proto_stats_proto_depIdxs,
		MessageInfos:      file_proto_stats_proto_msgTypes,
	}.Build()
	File_proto_stats_proto = out.File
	file_proto_stats_proto_goTypes = nil
	file_proto_stats_proto_depIdxs = nil
}
